spring:
  application:
    name: b-plus-studio
    version: '@project.version@'
    async:
      core-pool-size: 100
      max-pool-size: 150
      queue-capacity: 10000
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: false
  datasource:
    url: jdbc:postgresql://${EARNEST_DATABASE_HOSTNAME:localhost}:5432/${DATABASE_NAME:b-plus-studio}
#    ?sslmode=require
    username: ${DATABASE_USERNAME:}
#    password: ${DATABASE_PASSWORD:}
    driverClassName: org.postgresql.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations:
      - classpath:/db/migration

server:
  servlet:
    context-path: /b+studio
management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  override-with-generic-response: false
  default-produces-media-type: "application/json"
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha
  writer-with-order-by-keys: true
